<a href="https://colab.research.google.com/github/ananyapoonsawat/Python_dataviz2023/blob/main/Total_File_Homework_%26_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#จัดทำขึ้นโดยมีวัตถุประสงค์ที่จะรวบรวมการบ้าน และ ควิช

- HW 1 2 2.5 3 4
- Quiz 1 2 3

## HW 1
คำนวณว่าช่วงเวลาต่อไปนี้ห่างกันกี่ชั่วโมง กี่นาที กี่วินาที (printออกมาให้สวยงาม)

- 12:30:15 - 13:41:07
- 09:11:50 - 21:30:15
- 19:25:30 - 03:10:15

ข้อที่ 1 12:30:15 - 13:41:07

In [ ]:
q1 = '12:30:15'
Q1 = q1.split(":")
hours1 = int(Q1[0])*3600
minutes1 = int(Q1[1])*60
seconds1 = int(Q1[2])

q2 = '13:41:07'
Q2 = q2.split(":")
hours2 = int(Q2[0])*3600
minutes2 = int(Q2[1])*60
seconds2 = int(Q2[2])

a1 =  hours1 + minutes1 + seconds1
a2 =  hours2 + minutes2 + seconds2
a3 = a2 - a1

ho = int(a3/3600)
mi = int((a3%3600)/60)
se = int(a3%60)

print(f' ตั้งเเต่ 12:30:15 - 13:41:07 จะต่างกันเป็นเวลา {ho}ชั่วโมง {mi}นาที {se}วินาที')

 ตั้งเเต่ 12:30:15 - 13:41:07 จะต่างกันเป็นเวลา 1ชั่วโมง 10นาที 52วินาที


ข้อที่ 2 09:11:50 - 21:30:15

In [ ]:
q3 = '09:11:50'
Q3 = q3.split(":")
hours3 = int(Q3[0])*3600
minutes3 = int(Q3[1])*60
seconds3 = int(Q3[2])

q4 = '21:30:15'
Q4 = q4.split(":")
hours4 = int(Q4[0])*3600
minutes4 = int(Q4[1])*60
seconds4 = int(Q4[2])

a4 =  hours3 + minutes3 + seconds3
a5 =  hours4 + minutes4 + seconds4
a6 = a5 - a4

ho = int(a6/3600)
mi = int((a6%3600)/60)
se = int(a6%60)

print(f' ตั้งแต่ 09:11:50 - 21:30:15 จะต่างกันเป็นเวลา {ho}ชั่วโมง {mi}นาที {se}วินาที')

 ตั้งแต่ 09:11:50 - 21:30:15 จะต่างกันเป็นเวลา 12ชั่วโมง 18นาที 25วินาที


ข้อที่ 3 19:25:30 - 03:10:15

In [ ]:
q5 = '19:25:30'
Q5 = q5.split(":")
hours5 = int(Q5[0])*3600
minutes5 = int(Q5[1])*60
seconds5 = int(Q5[2])

q6 = '03:10:15'
Q6 = q6.split(":")
hours6 = int(Q6[0])*3600
minutes6 = int(Q6[1])*60
seconds6 = int(Q6[2])

a7 =  hours5 + minutes5 + seconds5
a8 =  hours6 + minutes6 + seconds6 + (24*60*60) #เกินเป็นอีกวัน
a9 = a8 - a7

ho = int(a9/3600)
mi = int((a9%3600)/60)
se = int(a9%60)

print(f'ตั้งแต่ 19:25:30 - 03:10:15 จะต่างกันเป็นเวลา {ho}ชั่วโมง {mi}นาที {se}วินาที')

ตั้งแต่ 19:25:30 - 03:10:15 จะต่างกันเป็นเวลา 7ชั่วโมง 44นาที 45วินาที


### ~~HW 2 , HW 2.5~~ (ของออม)

In [ ]:
import numpy as np
backgroup = 5
ก้าวไกล = backgroup * np.ones((16,13))
ก้าวไกล[1,1:12] = 99
ก้าวไกล[2,1:12] = 99
ก้าวไกล[3,10:12] = 99
ก้าวไกล[4,10:12] = 99
ก้าวไกล[5,10:12] = 99
ก้าวไกล[6,10:12] = 99
ก้าวไกล[7,9:11] = 99
ก้าวไกล[8,8:10] = 99
ก้าวไกล[9,7:9] = 99
ก้าวไกล[10,6:8] = 99
ก้าวไกล[11,5:7] = 99
ก้าวไกล[12,4:6] = 99
ก้าวไกล[13,3:5] = 99
ก้าวไกล[14,2:4] = 99
ก้าวไกล[15,1:3] = 99
ก้าวไกล[4,1:9] = 99
ก้าวไกล[5,1:9] = 99
ก้าวไกล[6,7:9] = 99
ก้าวไกล[7,6:8] = 99
ก้าวไกล[8,5:7] = 99
ก้าวไกล[9,4:6] = 99
ก้าวไกล[10,3:5] = 99
ก้าวไกล[11,2:4] = 99
ก้าวไกล[12,1:3] = 99
ก้าวไกล[13,1:2] = 99
ก้าวไกล

array([[ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 5., 99., 99., 99., 99., 99., 99., 99., 99., 99., 99., 99.,  5.],
       [ 5., 99., 99., 99., 99., 99., 99., 99., 99., 99., 99., 99.,  5.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5., 99., 99.,  5.],
       [ 5., 99., 99., 99., 99., 99., 99., 99., 99.,  5., 99., 99.,  5.],
       [ 5., 99., 99., 99., 99., 99., 99., 99., 99.,  5., 99., 99.,  5.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5., 99., 99.,  5., 99., 99.,  5.],
       [ 5.,  5.,  5.,  5.,  5.,  5., 99., 99.,  5., 99., 99.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5., 99., 99.,  5., 99., 99.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5., 99., 99.,  5., 99., 99.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5., 99., 99.,  5., 99., 99.,  5.,  5.,  5.,  5.,  5.],
       [ 5.,  5., 99., 99.,  5., 99., 99.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 5., 99., 99.,  5., 99., 99.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 5., 99.,  5., 99., 99.,  5., 

## HW 2
1. สร้าง array ที่เป็นรูป โลโกพักก้าวไกล (ของโอมมี่)

In [ ]:
import numpy as np

def print_kaokai(numbg = 0):
  int_bg = int(numbg)
  num_logo = 99
  MFP_17 = int_bg*np.ones((17,17))

  #outter 7
  #ขอบบน ---
  MFP_17[0:1, 0:17] = num_logo
  MFP_17[1:2, 1:16] = num_logo

  # /
  MFP_17[1:3, 14:16] = num_logo
  MFP_17[3:5, 13:15] = num_logo
  MFP_17[5:7, 12:14] = num_logo
  MFP_17[7:9, 11:13] = num_logo
  MFP_17[9:11, 10:12] = num_logo
  MFP_17[11:13, 9:11] = num_logo
  MFP_17[13:15, 8:10] = num_logo

  # เก็บหาง
  MFP_17[14:15, 7:10] = num_logo
  MFP_17[15:17, 8:9] = num_logo


  #inner 7
  #ขอบบน ---
  MFP_17[4:5, 2:11] = num_logo
  MFP_17[5:6, 3:10] = num_logo

  # /
  MFP_17[5:7, 8:10] = num_logo
  MFP_17[7:9, 7:9] = num_logo
  MFP_17[9:11, 6:8] = num_logo

  #เก็บหาง
  MFP_17[10:11, 5:8] = num_logo
  MFP_17[11:13, 6:7] = num_logo
  print(MFP_17)

print_kaokai(5)

[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 5. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5. 99. 99.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5. 99. 99.  5.  5.]
 [ 5.  5. 99. 99. 99. 99. 99. 99. 99. 99. 99.  5.  5. 99. 99.  5.  5.]
 [ 5.  5.  5. 99. 99. 99. 99. 99. 99. 99.  5.  5. 99. 99.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5. 99. 99.  5.  5. 99. 99.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5. 99. 99.  5.  5. 99. 99.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5. 99. 99.  5.  5. 99. 99.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5. 99. 99.  5.  5. 99. 99.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5. 99. 99. 99.  5.  5. 99. 99.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5. 99.  5.  5. 99. 99.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5. 99.  5.  5. 99. 99.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5. 99. 99.  5.  5.  5.  5.  5.  5.  5.]
 [ 5. 

In [ ]:
print_kaokai() #แบบไม่ใส่พื้นหลัง 2

[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 0. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 99. 99.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 99. 99.  0.  0.]
 [ 0.  0. 99. 99. 99. 99. 99. 99. 99. 99. 99.  0.  0. 99. 99.  0.  0.]
 [ 0.  0.  0. 99. 99. 99. 99. 99. 99. 99.  0.  0. 99. 99.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 99. 99.  0.  0. 99. 99.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 99. 99.  0.  0. 99. 99.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 99. 99.  0.  0. 99. 99.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 99. 99.  0.  0. 99. 99.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 99. 99. 99.  0.  0. 99. 99.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 99.  0.  0. 99. 99.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 99.  0.  0. 99. 99.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 99. 99.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 

## HW2.5
สร้าง Function เพื่อ print logo พรรคก้าวไกล โดย input พื้นหลังได้ (ของโอมมี่)

In [ ]:
print_kaokai(9) #แบบใส่พื้นหลัง 2.5

[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 9. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.  9.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9. 99. 99.  9.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9. 99. 99.  9.  9.]
 [ 9.  9. 99. 99. 99. 99. 99. 99. 99. 99. 99.  9.  9. 99. 99.  9.  9.]
 [ 9.  9.  9. 99. 99. 99. 99. 99. 99. 99.  9.  9. 99. 99.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9.  9.  9. 99. 99.  9.  9. 99. 99.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9.  9. 99. 99.  9.  9. 99. 99.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9.  9. 99. 99.  9.  9. 99. 99.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9. 99. 99.  9.  9. 99. 99.  9.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9. 99. 99. 99.  9.  9. 99. 99.  9.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9. 99.  9.  9. 99. 99.  9.  9.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9. 99.  9.  9. 99. 99.  9.  9.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9.  9.  9. 99. 99.  9.  9.  9.  9.  9.  9.  9.]
 [ 9. 

## HW 3
จากdata1 อยากรู้ว่า

1. รายการที่แพงและถูกที่สุดคือรายการไหน
2. รายการขุดลอกคูคลองของ 'สำนักงานเขตคลองสาน' และ 'สำนักงานเขตคลองสามวา'
3. จากข้อ 2 เขตไหนใช้งบประมาณ เยอะกว่ากัน
4. Core Budget ไหน ("12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม','17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร','28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต') มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive') # mount =  เชื่อมไดร์ฟ

Mounted at /content/drive


In [ ]:
data1 = pd.read_csv('/content/drive/MyDrive/DataViz23Data/BKK.csv')
data1.head()

Budget_resource  Issue_No  Fiscal_year  Department_code        Department  \
0       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
1       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
2       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
3       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
4       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   

                                    Core_budget_code Expenditure_category  \
0  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
1  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
2  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
3  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
4  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   

                                           Item_name  Approved_buget  
0        ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ         1193000  
1  ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...         1100000  
2          ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข         3075000  
3  ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...         6240000  
4  ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...         2685000

ข้อที่ 1 รายการที่แพงและถูกที่สุดคือรายการไหน

In [ ]:
data1_max = data1['Approved_buget'].max()
data1_min = data1['Approved_buget'].min()
data1[(data1['Approved_buget'] == data1_max) | (data1['Approved_buget'] == data1_min)]

Budget_resource  Issue_No  Fiscal_year  Department_code  \
576     งบเพิ่มเติม         1           66         11000000   
612     งบเพิ่มเติม         1           66         50180000   
613     งบเพิ่มเติม         1           66         50180000   
631     งบเพิ่มเติม         1           66         50240000   

                 Department Core_budget_code Expenditure_category  \
576        สำนักการระบายน้ำ              NaN              งบลงทุน   
612       สำนักงานเขตธนบุรี              NaN              งบลงทุน   
613       สำนักงานเขตธนบุรี              NaN              งบลงทุน   
631  สำนักงานเขตราษฎร์บูรณะ              NaN              งบลงทุน   

                                             Item_name  Approved_buget  
576  ขุดลอกคลองพระยาสุเรนทร์ จากคลองหกวาถึงคลองบางช...        28500000  
612  ขุดลอกลำกระโดงอำนวยสุข จากคลองบางกอกใหญ่ถึงสุด...               0  
613  ขุดลอกคลองแยกวัดประดู่ จากคลองบางกอกใหญ่ถึงคลอ...               0  
631   ขุดลอกคลองต้นโศกจากคลองราษฎร์บูรณะถึงคลองแจงร้อน               0

ข้อที่ 2 รายการขุดลอกคูคลองของ 'สำนักงานเขตคลองสาน' และ 'สำนักงานเขตคลองสามวา'

In [ ]:
df = pd.DataFrame(data1,columns=['Department','Item_name'])
df.set_index('Department', inplace=True)
result = df.loc[["สำนักงานเขตคลองสามวา","สำนักงานเขตคลองสาน"],['Item_name']]
result

Item_name
Department                                                             
สำนักงานเขตคลองสามวา  ขุดลอกคลองสามตะวันตก จากคลองสามวา ถึงคลองพระยา...
สำนักงานเขตคลองสามวา  ขุดลอกคลองสี่ตะวันตก จากคลองสามวา ถึงคลองพระยา...
สำนักงานเขตคลองสามวา  ขุดลอกลำรางวัดแป้นทอง จากคลองสี่ตะวันตก ถึงคลอ...
สำนักงานเขตคลองสามวา  ขุดลอกลำรางครูพัว จากคลองสองตะวันตก ถึงคลองหนึ...
สำนักงานเขตคลองสามวา     ขุดลอกลำรางตาชม จากคลองลำควายตาย ถึงคลองบางชัน
สำนักงานเขตคลองสามวา  ขุดลอกคลองเจ๊ก จากคลองหนึ่งตะวันตก ถึงสุดเขตคล...
สำนักงานเขตคลองสามวา  ขุดลอกคลองซอยเชื่อมคลองลำแบนกับคลองหนองระแหง จ...
สำนักงานเขตคลองสามวา                                   ขุดลอกลำรางตาเชย
สำนักงานเขตคลองสามวา                              ขุดลอกลำรางไทยเอราวัณ
สำนักงานเขตคลองสามวา                             ขุดลอกคลองหนึ่งตะวันตก
สำนักงานเขตคลองสามวา                               ขุดลอกคลองสองตะวันตก
สำนักงานเขตคลองสามวา                                   ขุดลอกคลองกีบหมู
สำนักงานเขตคลองสามวา                                 ขุดลอกคลองลำกะโหลก
สำนักงานเขตคลองสามวา                                 ขุดลอกคลองผักกะเฉด
สำนักงานเขตคลองสามวา                            ขุดลอกคลองบึงทรายกองดิน
สำนักงานเขตคลองสามวา                                  ขุดลอกลำรางซาฟารี
สำนักงานเขตคลองสามวา                                ขุดลอกลำรางตาจันทร์
สำนักงานเขตคลองสาน                                   ขุดลอกคูน้ำสารภี 1
สำนักงานเขตคลองสาน                              ขุดลอกคลองวัดทองเพลง\n 
สำนักงานเขตคลองสาน    ขุดลอกลำกระโดงชุมชนสองร้อยห้อง\nจากบริเวณบ้านเ...
สำนักงานเขตคลองสาน    ขุดลอกคลองวัดทองธรรมชาติและคลองแยกคลองวัดทองธร...
สำนักงานเขตคลองสาน                                     ขุดลอกคลองโรงปลา
สำนักงานเขตคลองสาน                           ขุดลอกลำกระโดงซอยอิสรภาพ 3
สำนักงานเขตคลองสาน         ขุดลอกคลองหลังวัดพิชัยญาติและคลองวัดน้อยเก่า
สำนักงานเขตคลองสาน                                  ขุดลอกคลองพระยาเกษม
สำนักงานเขตคลองสาน                      ขุดลอกคลองข้างโรงเรียนปทุมวิทยา
สำนักงานเขตคลองสาน    ขุดลอกคลองวัดน้อยใหม่จากแยกบ้านแขกถึงคลองสมเด็...
สำนักงานเขตคลองสาน    ขุดลอกคลองโรงหนัง จากคลองบางไส้ไก่ถึงแม่น้ำเจ้...
สำนักงานเขตคลองสาน    ขุดลอกคลองข้างโรงน้ำแข็ง จากสุดระยะคลองถึงแม่น...
สำนักงานเขตคลองสาน    ขุดลอกคลองข้างวัดอนงค์ จากคลองหลัง\nวัดพิชัยญา...

ข้อที่ 3 จากข้อ 2 เขตไหนใช้งบประมาณ เยอะกว่ากัน

In [ ]:
df3 = pd.DataFrame(data1)
result3 = df3.groupby('Department')['Approved_buget'].aggregate(['min','max'])
result3[0:3][1:3]

min      max
Department                           
สำนักงานเขตคลองสาน     80000  2218000
สำนักงานเขตคลองสามวา  452300  9832000

ข้อที่ 4 Core Budget ไหน ("12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม','17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร','28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต') มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด

In [ ]:
Core_data1

Budget_resource  Issue_No  Fiscal_year  Department_code  \
0         งบประจำปี         0           62         11000000   
1         งบประจำปี         0           62         11000000   
2         งบประจำปี         0           62         11000000   
3         งบประจำปี         0           62         11000000   
4         งบประจำปี         0           62         11000000   
..              ...       ...          ...              ...   
261       งบประจำปี         0           64         50500000   
262       งบประจำปี         0           64         50500000   
263       งบประจำปี         0           64         50500000   
264       งบประจำปี         0           64         50500000   
265       งบประจำปี         0           64         50500000   

            Department                                   Core_budget_code  \
0     สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
1     สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
2     สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
3     สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
4     สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
..                 ...                                                ...   
261  สำนักงานเขตบางบอน                                                  -   
262  สำนักงานเขตบางบอน                                                  -   
263  สำนักงานเขตบางบอน                                                  -   
264  สำนักงานเขตบางบอน                                                  -   
265  สำนักงานเขตบางบอน                                                  -   

    Expenditure_category                                          Item_name  \
0                งบลงทุน        ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ   
1                งบลงทุน  ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...   
2                งบลงทุน          ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข   
3                งบลงทุน  ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...   
4                งบลงทุน  ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...   
..                   ...                                                ...   
261              งบลงทุน                                   ขุดลอกคลองนายผล    
262              งบลงทุน                                 ขุดลอกคลองบางด้วน    
263              งบลงทุน  ขุดลอกคลองเนตรนุสรณ์ จากคลองบางบอนถึงสุดเขตกรุ...   
264              งบลงทุน                                    ขุดลอกคลองควาย    
265              งบลงทุน                               ขุดลอกคลองโคกกะวะดี    

     Approved_buget  
0           1193000  
1           1100000  
2           3075000  
3           6240000  
4           2685000  
..              ...  
261          488000  
262          410000  
263          978000  
264          498000  
265          486000  

[266 rows x 9 columns]

In [ ]:
Core_data1 = data1.dropna()
CoreBudget_data1 = Core_data1[Core_data1['Core_budget_code'] != '-']
CoreBudget_data1_12 =CoreBudget_data1[CoreBudget_data1['Core_budget_code'] == '12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม']
CoreBudget_data1_28 =CoreBudget_data1[CoreBudget_data1['Core_budget_code'] == '28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต']
CoreBudget_data1_17 =CoreBudget_data1[CoreBudget_data1['Core_budget_code'] == '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร']
CoreBudget = []

In [ ]:
x=set(CoreBudget_data1['Core_budget_code'])
for n in x:
  CoreBudget.append(n)
CoreBudget_data1_12_MEAN =CoreBudget_data1_12['Approved_buget'].mean()
CoreBudget_data1_17_MEAN =CoreBudget_data1_17['Approved_buget'].mean()
CoreBudget_data1_28_MEAN =CoreBudget_data1_28['Approved_buget'].mean()

In [ ]:
if (CoreBudget_data1_12_MEAN > CoreBudget_data1_17_MEAN ) & (CoreBudget_data1_12_MEAN > CoreBudget_data1_28_MEAN ):
  print(f'รายการนี้ {CoreBudget[2]} มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด {CoreBudget_data1_12_MEAN}')
elif (CoreBudget_data1_17_MEAN > CoreBudget_data1_12_MEAN ) & (CoreBudget_data1_17_MEAN > CoreBudget_data1_28_MEAN ):
  print(f'รายการนี้ {CoreBudget[0]} มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด {CoreBudget_data1_17_MEAN}')
elif (CoreBudget_data1_28_MEAN > CoreBudget_data1_12_MEAN ) & (CoreBudget_data1_28_MEAN > CoreBudget_data1_17_MEAN ):
  print(f'รายการนี้ {CoreBudget[1]} มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด {CoreBudget_data1_28_MEAN}')

รายการนี้ 28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด 1837500.0


## HW 4
จากตาราง sep_oct_df

1. งบประมาณประจำหรืองบประมาณลงทุน สูงกว่ากัน
2. งบรวม เดือน oct หรืแ sep อันไหนมากกว่ากัน
3. แก้ค่า missing พร้อมทั้งให้เหตุผล
4. เดือนไหนเบิกจ่ายมากกว่ากัน (การใช้จ่าย (PO+เบิกจ่าย))


In [ ]:
import pandas as pd
import os

In [ ]:

from google.colab import drive # เชื่อมบัญชีกับ google drive #ต้องเอาไฟล์ที่ต้องการไปใส่ก่อน
drive.mount('/content/drive') # เช็คว่าเชื่อมติดหรือไม่

Mounted at /content/drive


ข้อที่ 1 งบประมาณประจำหรืองบประมาณลงทุน สูงกว่ากัน

In [ ]:
sep_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/sep65.xlsx',header=8,skipfooter=26) #เรียกใช้ไฟล์ที่ต้องการ และ ตั้งหัวตาราง
sep_df
sep_df1 = sep_df[(sep_df['รายการ'] == 'ประจำ') | (sep_df['รายการ'] == 'ลงทุน')]
sep_df1

รายการ      งบประมาณ  สำรองเงินมีหนี้            PO      เบิกจ่าย  \
2  ประจำ  1.892013e+10     7.925745e+07  7.131600e+07  1.880196e+10   
3  ลงทุน  9.605258e+09     2.683430e+08  1.119320e+09  8.201965e+09   

   ร้อยละ\nเบิกจ่าย  เป้า\nหมาย Q4  */- เป้าหมาย  การใช้จ่าย (PO+เบิกจ่าย)  \
2         99.375405           98.0      1.375405              1.895253e+10   
3         85.390363           75.0     10.390363              9.589628e+09   

   ร้อยละ\nการใช้จ่าย  ...  ลำดับ\nใช้จ่าย  Unnamed: 15  รายการ.1  \
2          100.171242  ...             NaN          NaN     ประจำ   
3           99.837275  ...            15.0         13.0     ลงทุน   

     งบประมาณ.1    ผลเบิกจ่าย  ร้อยละเบิกจ่าย  สูงกว่าเป้าหมาย  ผลการใช้จ่าย  \
2  12452.794570  10580.839075        84.967587       27.967587  10614.976114   
3   9211.127432   4679.609100        50.803869       21.803869    7454.33853   

      ร้อยละ  สูงกว่าเป้าหมาย.1  
2  85.241719          29.461719  
3  80.927537          22.777537  

[2 rows x 24 columns]

In [ ]:
oct_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/oct65.xlsx',header=9,skipfooter=27) #เรียกใช้ไฟล์ที่ต้องการ และ ตั้งหัวตาราง
oct_df
oct_df1 = oct_df[(oct_df['รายการ'] == 'ประจำ') | (oct_df['รายการ'] == 'ลงทุน')]
oct_df1

รายการ     งบประมาณ  สำรองเงินมีหนี้          PO     เบิกจ่าย  \
2  ประจำ  6822.811789              NaN   12.706842  3984.779058   
3  ลงทุน  6180.211723              NaN  457.295806  1291.209026   

   ร้อยละ\nเบิกจ่าย  เป้า\nหมาย Q1  */- เป้าหมาย  การใช้จ่าย (PO+เบิกจ่าย)  \
2         58.403766           35.0     23.403766               3997.485900   
3         20.892634           19.0      1.892634               1748.504832   

   ร้อยละ\nการใช้จ่าย  เป้า\nหมาย Q1.1  */- เป้าหมาย.1  \
2           58.590007            35.33       23.260007   
3           28.291989            28.96       -0.668011   

   คงเหลือ\nหลังหักใช้จ่าย  ลำดับเบิกจ่าย  ลำดับ\nใช้จ่าย  
2              2825.325889            NaN             NaN  
3              4431.706890            4.0             6.0

In [ ]:
sep_oct_df = pd.concat([sep_df,oct_df])
sep_oct_df

รายการ      งบประมาณ  สำรองเงินมีหนี้  \
0  งบประมาณรายจ่ายประจำปี พ.ศ.2565           NaN              NaN   
1                           ภาพรวม  2.852539e+10     3.476005e+08   
2                            ประจำ  1.892013e+10     7.925745e+07   
3                            ลงทุน  9.605258e+09     2.683430e+08   
0  งบประมาณรายจ่ายประจำปี พ.ศ.2565           NaN              NaN   
1                           ภาพรวม  1.300302e+04              NaN   
2                            ประจำ  6.822812e+03              NaN   
3                            ลงทุน  6.180212e+03              NaN   

             PO      เบิกจ่าย  ร้อยละ\nเบิกจ่าย  เป้า\nหมาย Q4  */- เป้าหมาย  \
0           NaN           NaN               NaN            NaN           NaN   
1  1.190636e+09  2.700392e+10         94.666269           93.0      1.666269   
2  7.131600e+07  1.880196e+10         99.375405           98.0      1.375405   
3  1.119320e+09  8.201965e+09         85.390363           75.0     10.390363   
0           NaN           NaN               NaN            NaN           NaN   
1  4.700026e+02  5.275988e+03         40.575087            NaN      8.575087   
2  1.270684e+01  3.984779e+03         58.403766            NaN     23.403766   
3  4.572958e+02  1.291209e+03         20.892634            NaN      1.892634   

   การใช้จ่าย (PO+เบิกจ่าย)  ร้อยละ\nการใช้จ่าย  ...  รายการ.1    งบประมาณ.1  \
0                       NaN                 NaN  ...       NaN           NaN   
1              2.854216e+10          100.058786  ...    ภาพรวม  21663.922002   
2              1.895253e+10          100.171242  ...     ประจำ  12452.794570   
3              9.589628e+09           99.837275  ...     ลงทุน   9211.127432   
0                       NaN                 NaN  ...       NaN           NaN   
1              5.745991e+03           44.189651  ...       NaN           NaN   
2              3.997486e+03           58.590007  ...       NaN           NaN   
3              1.748505e+03           28.291989  ...       NaN           NaN   

     ผลเบิกจ่าย  ร้อยละเบิกจ่าย   สูงกว่าเป้าหมาย     ผลการใช้จ่าย  \
0           NaN              NaN        ไตรมาส 2   (PO + เบิกจ่าย)   
1  15260.448175        70.441761        19.441761     18069.314644   
2  10580.839075        84.967587        27.967587     10614.976114   
3   4679.609100        50.803869        21.803869       7454.33853   
0           NaN              NaN              NaN              NaN   
1           NaN              NaN              NaN              NaN   
2           NaN              NaN              NaN              NaN   
3           NaN              NaN              NaN              NaN   

       ร้อยละ  สูงกว่าเป้าหมาย.1  เป้า\nหมาย Q1  เป้า\nหมาย Q1.1  
0  การใช้จ่าย           ไตรมาส 2            NaN              NaN  
1   83.407403          27.167403            NaN              NaN  
2   85.241719          29.461719            NaN              NaN  
3   80.927537          22.777537            NaN              NaN  
0         NaN                NaN            NaN              NaN  
1         NaN                NaN           32.0            34.08  
2         NaN                NaN           35.0            35.33  
3         NaN                NaN           19.0            28.96  

[8 rows x 26 columns]

In [ ]:
sep_oct_df1 = pd.concat([sep_df1,oct_df1])
sep_oct_df1

รายการ      งบประมาณ  สำรองเงินมีหนี้            PO      เบิกจ่าย  \
2  ประจำ  1.892013e+10     7.925745e+07  7.131600e+07  1.880196e+10   
3  ลงทุน  9.605258e+09     2.683430e+08  1.119320e+09  8.201965e+09   
2  ประจำ  6.822812e+03              NaN  1.270684e+01  3.984779e+03   
3  ลงทุน  6.180212e+03              NaN  4.572958e+02  1.291209e+03   

   ร้อยละ\nเบิกจ่าย  เป้า\nหมาย Q4  */- เป้าหมาย  การใช้จ่าย (PO+เบิกจ่าย)  \
2         99.375405           98.0      1.375405              1.895253e+10   
3         85.390363           75.0     10.390363              9.589628e+09   
2         58.403766            NaN     23.403766              3.997486e+03   
3         20.892634            NaN      1.892634              1.748505e+03   

   ร้อยละ\nการใช้จ่าย  ...  รายการ.1    งบประมาณ.1    ผลเบิกจ่าย  \
2          100.171242  ...     ประจำ  12452.794570  10580.839075   
3           99.837275  ...     ลงทุน   9211.127432   4679.609100   
2           58.590007  ...       NaN           NaN           NaN   
3           28.291989  ...       NaN           NaN           NaN   

   ร้อยละเบิกจ่าย   สูงกว่าเป้าหมาย  ผลการใช้จ่าย     ร้อยละ  \
2        84.967587        27.967587  10614.976114  85.241719   
3        50.803869        21.803869    7454.33853  80.927537   
2              NaN              NaN           NaN        NaN   
3              NaN              NaN           NaN        NaN   

   สูงกว่าเป้าหมาย.1  เป้า\nหมาย Q1  เป้า\nหมาย Q1.1  
2          29.461719            NaN              NaN  
3          22.777537            NaN              NaN  
2                NaN           35.0            35.33  
3                NaN           19.0            28.96  

[4 rows x 26 columns]

In [ ]:
sep_df2 = sep_df1[['รายการ','งบประมาณ']]
oct_df2 = oct_df1[['รายการ','งบประมาณ']]

In [ ]:
sep_oct_df2 = pd.concat([sep_df2,oct_df2])
sep_oct_df2

รายการ      งบประมาณ
2  ประจำ  1.892013e+10
3  ลงทุน  9.605258e+09
2  ประจำ  6.822812e+03
3  ลงทุน  6.180212e+03

In [ ]:
so0 =sep_oct_df2[sep_oct_df2['รายการ'] != '-']
so1 =so0[so0['รายการ'] == 'ประจำ']
so2 =so0[so0['รายการ'] == 'ลงทุน']
sepoct00 = []
x = set(so0['รายการ'])
for n in x:
    sepoct00.append(n)
so1 =so1['งบประมาณ'].mean()
so2 =so2['งบประมาณ'].mean()
if (so2 > so1):
  print(f'รายการ {sepoct00[0]} ในเดือนกันยายนมีงบประมาณสูงกว่า {sepoct00[1]}')
elif (so1 > so2):
  print(f'รายการ {sepoct00[1]} ในเดือนกันยายนมีงบประมาณสูงกว่า {sepoct00[0]}')

รายการ ลงทุน ในเดือนกันยายนมีงบประมาณสูงกว่า ประจำ


In [ ]:
sep_oct_df1.describe()

งบประมาณ  สำรองเงินมีหนี้            PO      เบิกจ่าย  \
count  4.000000e+00     2.000000e+00  4.000000e+00  4.000000e+00   
mean   7.131351e+09     1.738002e+08  2.976592e+08  6.750982e+09   
std    9.070239e+09     1.337037e+08  5.488047e+08  8.915956e+09   
min    6.180212e+03     7.925745e+07  1.270684e+01  1.291209e+03   
25%    6.662162e+03     1.265288e+08  3.461486e+02  3.311387e+03   
50%    4.802632e+09     1.738002e+08  3.565823e+07  4.100984e+09   
75%    1.193398e+10     2.210716e+08  3.333170e+08  1.085196e+10   
max    1.892013e+10     2.683430e+08  1.119320e+09  1.880196e+10   

       ร้อยละ\nเบิกจ่าย  เป้า\nหมาย Q4  */- เป้าหมาย  \
count          4.000000       2.000000      4.000000   
mean          66.015542      86.500000      9.265542   
std           34.555656      16.263456     10.291884   
min           20.892634      75.000000      1.375405   
25%           49.025983      80.750000      1.763327   
50%           71.897065      86.500000      6.141499   
75%           88.886624      92.250000     13.643714   
max           99.375405      98.000000     23.403766   

       การใช้จ่าย (PO+เบิกจ่าย)  ร้อยละ\nการใช้จ่าย  เป้า\nหมาย Q4.1  \
count              4.000000e+00            4.000000              2.0   
mean               7.135541e+09           71.722628            100.0   
std                9.082870e+09           34.921069              0.0   
min                1.748505e+03           28.291989            100.0   
25%                3.435241e+03           51.015502            100.0   
50%                4.794816e+09           79.213641            100.0   
75%                1.193035e+10           99.920767            100.0   
max                1.895253e+10          100.171242            100.0   

       */- เป้าหมาย.1  คงเหลือ\nหลังหักใช้จ่าย  ลำดับเบิกจ่าย  ลำดับ\nใช้จ่าย  \
count        4.000000             4.000000e+00       2.000000        2.000000   
mean         5.650128            -4.190447e+06       5.000000       10.500000   
std         11.744987             2.019710e+07       1.414214        6.363961   
min         -0.668011            -3.239918e+07       4.000000        6.000000   
25%         -0.289046            -8.097675e+06       4.500000        8.250000   
50%          0.004259             3.628516e+03       5.000000       10.500000   
75%          5.943433             3.910856e+06       5.500000       12.750000   
max         23.260007             1.563013e+07       6.000000       15.000000   

       Unnamed: 15    งบประมาณ.1    ผลเบิกจ่าย  ร้อยละเบิกจ่าย   \
count          1.0      2.000000      2.000000         2.000000   
mean          13.0  10831.961001   7630.224087        67.885728   
std            NaN   2292.204816   4172.799733        24.157397   
min           13.0   9211.127432   4679.609100        50.803869   
25%           13.0  10021.544216   6154.916594        59.344798   
50%           13.0  10831.961001   7630.224087        67.885728   
75%           13.0  11642.377786   9105.531581        76.426658   
max           13.0  12452.794570  10580.839075        84.967587   

       เป้า\nหมาย Q1  เป้า\nหมาย Q1.1  
count       2.000000          2.00000  
mean       27.000000         32.14500  
std        11.313708          4.50427  
min        19.000000         28.96000  
25%        23.000000         30.55250  
50%        27.000000         32.14500  
75%        31.000000         33.73750  
max        35.000000         35.33000

ข้อที่ 2 งบรวม(งบประมาณรวม) เดือน oct หรือ sep อันไหนมากกว่ากัน

In [42]:
sep_oct_df1 = pd.concat([sep_df1,oct_df1])
sep_oct_df1

รายการ      งบประมาณ  สำรองเงินมีหนี้            PO      เบิกจ่าย  \
2  ประจำ  1.892013e+10     7.925745e+07  7.131600e+07  1.880196e+10   
3  ลงทุน  9.605258e+09     2.683430e+08  1.119320e+09  8.201965e+09   
2  ประจำ  6.822812e+03              NaN  1.270684e+01  3.984779e+03   
3  ลงทุน  6.180212e+03              NaN  4.572958e+02  1.291209e+03   

   ร้อยละ\nเบิกจ่าย  เป้า\nหมาย Q4  */- เป้าหมาย  การใช้จ่าย (PO+เบิกจ่าย)  \
2         99.375405           98.0      1.375405              1.895253e+10   
3         85.390363           75.0     10.390363              9.589628e+09   
2         58.403766            NaN     23.403766              3.997486e+03   
3         20.892634            NaN      1.892634              1.748505e+03   

   ร้อยละ\nการใช้จ่าย  ...  รายการ.1    งบประมาณ.1    ผลเบิกจ่าย  \
2          100.171242  ...     ประจำ  12452.794570  10580.839075   
3           99.837275  ...     ลงทุน   9211.127432   4679.609100   
2           58.590007  ...       NaN           NaN           NaN   
3           28.291989  ...       NaN           NaN           NaN   

   ร้อยละเบิกจ่าย   สูงกว่าเป้าหมาย  ผลการใช้จ่าย     ร้อยละ  \
2        84.967587        27.967587  10614.976114  85.241719   
3        50.803869        21.803869    7454.33853  80.927537   
2              NaN              NaN           NaN        NaN   
3              NaN              NaN           NaN        NaN   

   สูงกว่าเป้าหมาย.1  เป้า\nหมาย Q1  เป้า\nหมาย Q1.1  
2          29.461719            NaN              NaN  
3          22.777537            NaN              NaN  
2                NaN           35.0            35.33  
3                NaN           19.0            28.96  

[4 rows x 26 columns]

In [43]:
sepbud_df = sep_df1[['รายการ','งบประมาณ']]
sepbud_df

รายการ      งบประมาณ
2  ประจำ  1.892013e+10
3  ลงทุน  9.605258e+09

In [44]:
octbud_df = oct_df1[['รายการ','งบประมาณ']]
octbud_df

รายการ     งบประมาณ
2  ประจำ  6822.811789
3  ลงทุน  6180.211723

In [45]:
sep_oct_dfbud = pd.concat([sepbud_df,octbud_df])
sep_oct_dfbud

รายการ      งบประมาณ
2  ประจำ  1.892013e+10
3  ลงทุน  9.605258e+09
2  ประจำ  6.822812e+03
3  ลงทุน  6.180212e+03

In [48]:
sepbud0 = sepbud_df[sepbud_df['รายการ']!= '-']
sepbud1 = sepbud0[sepbud0['รายการ'] == 'ประจำ']
sepbud2 = sepbud0[sepbud0['รายการ'] == 'ลงทุน']
sepbud = []

x = set(sepbud0['รายการ'])
for n in x:
    sepbud.append(n)
sepbud1 =sepbud1['งบประมาณ'].mean()
sepbud2 =sepbud2['งบประมาณ'].mean()
sepbud3 = sepbud1+sepbud2

print(f'เดือน{sepbudget} มีงบประมาณรวม {sepbud3} บาท')

เดือนกันยายน มีงบประมาณรวม 28525389387.86998 บาท


In [49]:
octbud0 = octbud_df[octbud_df['รายการ']!= '-']
octbud1 = octbud0[octbud0['รายการ'] == 'ประจำ']
octbud2 = octbud0[octbud0['รายการ'] == 'ลงทุน']
octbud = []

x = set(octbud0['รายการ'])
for n in x:
    octbud.append(n)
octbud1 =octbud1['งบประมาณ'].mean()
octbud2 =octbud2['งบประมาณ'].mean()
octbud3 = octbud1+octbud2

print(f'เดือนตุลาคมมีงบประมาณรวม {octbud3} บาท')

เดือนตุลาคมมีงบประมาณรวม 13003.02351155 บาท


In [47]:
sepbudget = ('กันยายน')
octbudget = ('ตุลาคม')

In [50]:
sepoctbudget1=sepbud3-octbud3
sepoctbudget2=octbud3-sepbud3
sepoctbudget0=[sepoctbudget1,sepoctbudget2]
sepoctbudget0

[28525376384.84647, -28525376384.84647]

In [51]:
if (sepbud3 > octbud3):
  print(f'ในเดือน {sepbudget} มีงบประมาณรวมมากกว่าเดือน {octbudget} ทั้งหมด {sepoctbudget1} บาท')
elif (octbud3 > sepbud3):
  print(f'ในเดือน {octbudget} มีงบประมาณรวมมากกว่าเดือน {sepbudget}ทั้งหมด {sepoctbudget2} บาท')

ในเดือน กันยายน มีงบประมาณรวมมากกว่าเดือน ตุลาคม ทั้งหมด 28525376384.84647 บาท


ข้อที่ 4 เดือนไหนเบิกจ่ายมากกว่ากัน (การใช้จ่าย (PO+เบิกจ่าย))

In [ ]:
sep_oct_df1 = pd.concat([sep_df1,oct_df1])
sep_oct_df1

รายการ      งบประมาณ  สำรองเงินมีหนี้            PO      เบิกจ่าย  \
2  ประจำ  1.892013e+10     7.925745e+07  7.131600e+07  1.880196e+10   
3  ลงทุน  9.605258e+09     2.683430e+08  1.119320e+09  8.201965e+09   
2  ประจำ  6.822812e+03              NaN  1.270684e+01  3.984779e+03   
3  ลงทุน  6.180212e+03              NaN  4.572958e+02  1.291209e+03   

   ร้อยละ\nเบิกจ่าย  เป้า\nหมาย Q4  */- เป้าหมาย  การใช้จ่าย (PO+เบิกจ่าย)  \
2         99.375405           98.0      1.375405              1.895253e+10   
3         85.390363           75.0     10.390363              9.589628e+09   
2         58.403766            NaN     23.403766              3.997486e+03   
3         20.892634            NaN      1.892634              1.748505e+03   

   ร้อยละ\nการใช้จ่าย  ...  รายการ.1    งบประมาณ.1    ผลเบิกจ่าย  \
2          100.171242  ...     ประจำ  12452.794570  10580.839075   
3           99.837275  ...     ลงทุน   9211.127432   4679.609100   
2           58.590007  ...       NaN           NaN           NaN   
3           28.291989  ...       NaN           NaN           NaN   

   ร้อยละเบิกจ่าย   สูงกว่าเป้าหมาย  ผลการใช้จ่าย     ร้อยละ  \
2        84.967587        27.967587  10614.976114  85.241719   
3        50.803869        21.803869    7454.33853  80.927537   
2              NaN              NaN           NaN        NaN   
3              NaN              NaN           NaN        NaN   

   สูงกว่าเป้าหมาย.1  เป้า\nหมาย Q1  เป้า\nหมาย Q1.1  
2          29.461719            NaN              NaN  
3          22.777537            NaN              NaN  
2                NaN           35.0            35.33  
3                NaN           19.0            28.96  

[4 rows x 26 columns]

In [ ]:
sep_df3 = sep_df1[['รายการ','การใช้จ่าย (PO+เบิกจ่าย)']]
sep_df3

รายการ  การใช้จ่าย (PO+เบิกจ่าย)
2  ประจำ              1.895253e+10
3  ลงทุน              9.589628e+09

In [ ]:
oct_df3 = oct_df1[['รายการ','การใช้จ่าย (PO+เบิกจ่าย)']]
oct_df3

รายการ  การใช้จ่าย (PO+เบิกจ่าย)
2  ประจำ               3997.485900
3  ลงทุน               1748.504832

In [ ]:
sep_oct_df3 = pd.concat([sep_df3,oct_df3])
sep_oct_df3

รายการ  การใช้จ่าย (PO+เบิกจ่าย)
2  ประจำ              1.895253e+10
3  ลงทุน              9.589628e+09
2  ประจำ              3.997486e+03
3  ลงทุน              1.748505e+03

In [ ]:
sumsep0 = sep_df3[sep_df3['รายการ']!= '-']
sumsep1 = sumsep0[sumsep0['รายการ'] == 'ประจำ']
sumsep2 = sumsep0[sumsep0['รายการ'] == 'ลงทุน']
sepsum0 = []

x = set(sumsep0['รายการ'])
for n in x:
    sepsum0.append(n)
sumsep1 =sumsep1['การใช้จ่าย (PO+เบิกจ่าย)'].mean()
sumsep2 =sumsep2['การใช้จ่าย (PO+เบิกจ่าย)'].mean()
sumsep3 = sumsep1+sumsep2

print(f'เดือนกันยายนมีการเบิกจ่าย {sumsep3} บาท')

เดือนกันยายนมีการเบิกจ่าย 28542158434.179993 บาท


In [ ]:
sumoct0 = oct_df3[sep_df3['รายการ']!= '-']
sumoct1 = sumoct0[sumoct0['รายการ'] == 'ประจำ']
sumoct2 = sumoct0[sumoct0['รายการ'] == 'ลงทุน']
octsum0 = []

x = set(sumoct0['รายการ'])
for n in x:
    octsum0.append(n)
sumoct1 =sumoct1['การใช้จ่าย (PO+เบิกจ่าย)'].mean()
sumoct2 =sumoct2['การใช้จ่าย (PO+เบิกจ่าย)'].mean()
sumoct3 = sumoct1+sumoct2

print(f'เดือนตุลาคมมีการเบิกจ่าย {sumoct3} บาท')

เดือนตุลาคมมีการเบิกจ่าย 5745.990732730001 บาท


In [ ]:
sepsum0 = ('กันยายน')
octsum0 = ('ตุลาคม')

total1=sumsep3-sumoct3
total2=sumoct3-sumsep3
total0=[total1,total2]

In [ ]:
if (sumsep3 > sumoct3):
  print(f'เดือน {sepsum0} มีการเบิกจ่าย(การใช้จ่าย (PO+เบิกจ่าย)) มากกว่าเดือน {octsum0}ทั้งหมด {total1} บาท')
elif (sumoct3 > sumsep3):
  print(f'เดือน {octsum0} มีการเบิกจ่าย(การใช้จ่าย (PO+เบิกจ่าย)) มากกว่าเดือน {sepsum0}ทั้งหมด {total2} บาท')

เดือน กันยายน มีการเบิกจ่าย(การใช้จ่าย (PO+เบิกจ่าย)) มากกว่าเดือน ตุลาคมทั้งหมด 28542152688.18926 บาท


## Quiz 1

## Quiz 2

กำหนด list เป็นประโยคคำว่า "Department of Statistics, Faculty of Science, Khon Kaen University, Thailand"

1. ตัดมาเฉพาะคำว่า Faculty of Science
2. ตัดแบบเว้นทีละ 3 ตัวอักษร
3. ตัดคำว่า Khon Kaen University ออกมาแล้วเขียนกลับหลัง

In [ ]:
list_t = ["Department of Statistics, Faculty of Science, Khon Kaen University, Thailand"]
qtext = "Department of Statistics, Faculty of Science, Khon Kaen University, Thailand"
list_t2 = list("Department of Statistics, Faculty of Science, Khon Kaen University, Thailand")
list_t2

['D',
 'e',
 'p',
 'a',
 'r',
 't',
 'm',
 'e',
 'n',
 't',
 ' ',
 'o',
 'f',
 ' ',
 'S',
 't',
 'a',
 't',
 'i',
 's',
 't',
 'i',
 'c',
 's',
 ',',
 ' ',
 'F',
 'a',
 'c',
 'u',
 'l',
 't',
 'y',
 ' ',
 'o',
 'f',
 ' ',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e',
 ',',
 ' ',
 'K',
 'h',
 'o',
 'n',
 ' ',
 'K',
 'a',
 'e',
 'n',
 ' ',
 'U',
 'n',
 'i',
 'v',
 'e',
 'r',
 's',
 'i',
 't',
 'y',
 ',',
 ' ',
 'T',
 'h',
 'a',
 'i',
 'l',
 'a',
 'n',
 'd']

In [ ]:
qlist = qtext.split(', ')
qlist
list_t
type(list_t)
type(qtext)
type(list_t2)

list

In [ ]:
list_q2 = qtext.split(', ')
list_q2

['Department of Statistics',
 'Faculty of Science',
 'Khon Kaen University',
 'Thailand']

ข้อที่ 1 ตัดมาเฉพาะคำว่า Faculty of Science

In [ ]:
list_q2[0]

'Department of Statistics'

ข้อที่ 2 ตัดแบบเว้นทีละ 3 ตัวอักษร

In [ ]:
list_ch2 = list_t[::3]
list_ch2

['Department of Statistics, Faculty of Science, Khon Kaen University, Thailand']

ข้อที่ 3 ตัดคำว่า Khon Kaen University ออกมาแล้วเขียนกลับหลัง

In [ ]:
list_q2[2]
list_ch3 = list_q2[2][::-1]
list_ch3

'ytisrevinU neaK nohK'

## Quiz3
อยากได้รายการที่ได้รับอนุมัติงบมากกว่า 1 ล้านบาท แต่ไม่เกิน 2 ล้านบาท

In [ ]:

import pandas as pd #ฟังก์ชันเฉพาะต้องรันก่อน

In [ ]:
from google.colab import drive
drive.mount('/content/drive')  # mount =  เชื่อมไดร์ฟ

Mounted at /content/drive


In [ ]:
data0 = pd.read_csv('/content/drive/MyDrive/DataViz23Data/BKK.csv')

In [ ]:
data1 = pd.read_csv('/content/drive/MyDrive/DataViz23Data/BKK.csv')
data1.head()

Budget_resource  Issue_No  Fiscal_year  Department_code        Department  \
0       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
1       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
2       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
3       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
4       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   

                                    Core_budget_code Expenditure_category  \
0  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
1  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
2  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
3  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
4  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   

                                           Item_name  Approved_buget  
0        ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ         1193000  
1  ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...         1100000  
2          ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข         3075000  
3  ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...         6240000  
4  ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...         2685000

In [ ]:
data1[(data1['Approved_buget']>1000000) & (data1['Approved_buget'] <= 2000000)] #Answer

Budget_resource  Issue_No  Fiscal_year  Department_code  \
0         งบประจำปี         0           62         11000000   
1         งบประจำปี         0           62         11000000   
5         งบประจำปี         0           62         11000000   
22        งบประจำปี         0           63         11000000   
25        งบประจำปี         0           63         11000000   
..              ...       ...          ...              ...   
660     งบเพิ่มเติม         1           66         50350000   
662     งบเพิ่มเติม         1           66         50350000   
665     งบเพิ่มเติม         1           66         50350000   
666     งบเพิ่มเติม         1           66         50360000   
670     งบเพิ่มเติม         1           66         50360000   

             Department                                   Core_budget_code  \
0      สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
1      สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
5      สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
22     สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
25     สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
..                  ...                                                ...   
660  สำนักงานเขตบางพลัด                                                NaN   
662  สำนักงานเขตบางพลัด                                                NaN   
665  สำนักงานเขตบางพลัด                                                NaN   
666   สำนักงานเขตจอมทอง                                                NaN   
670   สำนักงานเขตจอมทอง                                                NaN   

    Expenditure_category                                          Item_name  \
0                งบลงทุน        ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ   
1                งบลงทุน  ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...   
5                งบลงทุน  ขุดลอกคลองราษฎร์สามัคคีจากคลองทวีวัฒนาถึงคลองม...   
22               งบลงทุน      ขุดลอกคลองนางหงษ์จากคลองแสนแสบถึงถนนบรรทัดทอง   
25               งบลงทุน  ขุดลอกคลองราษฎร์บูรณะจากแม่น้ำเจ้าพระยาถึงสวนธ...   
..                   ...                                                ...   
660              งบลงทุน                                 ขุดลอกคลองสะพานยาว   
662              งบลงทุน         ขุดลอกคลองบางรักและคูน้ำซอยจรัญสนิทวงศ์ 89   
665              งบลงทุน                           ขุดลอกคลองวัดน้อยนางหงษ์   
666              งบลงทุน  ขุดลอกคลองลัดบางสะแก (1),(2) จากคลองบางค้อและค...   
670              งบลงทุน  ขุดลอกลำกระโดงสาธารณประโยชน์แยกคลองต้นไทร (3),...   

     Approved_buget  
0           1193000  
1           1100000  
5           1207000  
22          1508000  
25          1975000  
..              ...  
660         1756000  
662         1859000  
665         1187000  
666         1581000  
670         1388000  

[132 rows x 9 columns]