<a href="https://colab.research.google.com/github/ananyapoonsawat/Python_dataviz2023/blob/main/Total_File_Homework_%26_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#จัดทำขึ้นโดยมีวัตถุประสงค์ที่จะรวบรวมการบ้าน และ ควิช

- HW 1 2 2.5 3 4
- Quiz 1 2 3

## HW 1
คำนวณว่าช่วงเวลาต่อไปนี้ห่างกันกี่ชั่วโมง กี่นาที กี่วินาที (printออกมาให้สวยงาม)

- 12:30:15 - 13:41:07
- 09:11:50 - 21:30:15
- 19:25:30 - 03:10:15

ข้อที่ 1 12:30:15 - 13:41:07

In [1]:
q1 = '12:30:15'
Q1 = q1.split(":")
hours1 = int(Q1[0])*3600
minutes1 = int(Q1[1])*60
seconds1 = int(Q1[2])

q2 = '13:41:07'
Q2 = q2.split(":")
hours2 = int(Q2[0])*3600
minutes2 = int(Q2[1])*60
seconds2 = int(Q2[2])

a1 =  hours1 + minutes1 + seconds1
a2 =  hours2 + minutes2 + seconds2
a3 = a2 - a1

ho = int(a3/3600)
mi = int((a3%3600)/60)
se = int(a3%60)

print(f' ตั้งเเต่ 12:30:15 - 13:41:07 จะต่างกันเป็นเวลา {ho}ชั่วโมง {mi}นาที {se}วินาที')

 ตั้งเเต่ 12:30:15 - 13:41:07 จะต่างกันเป็นเวลา 1ชั่วโมง 10นาที 52วินาที


ข้อที่ 2 09:11:50 - 21:30:15

In [2]:
q3 = '09:11:50'
Q3 = q3.split(":")
hours3 = int(Q3[0])*3600
minutes3 = int(Q3[1])*60
seconds3 = int(Q3[2])

q4 = '21:30:15'
Q4 = q4.split(":")
hours4 = int(Q4[0])*3600
minutes4 = int(Q4[1])*60
seconds4 = int(Q4[2])

a4 =  hours3 + minutes3 + seconds3
a5 =  hours4 + minutes4 + seconds4
a6 = a5 - a4

ho = int(a6/3600)
mi = int((a6%3600)/60)
se = int(a6%60)

print(f' ตั้งแต่ 09:11:50 - 21:30:15 จะต่างกันเป็นเวลา {ho}ชั่วโมง {mi}นาที {se}วินาที')

 ตั้งแต่ 09:11:50 - 21:30:15 จะต่างกันเป็นเวลา 12ชั่วโมง 18นาที 25วินาที


ข้อที่ 3 19:25:30 - 03:10:15

In [3]:
q5 = '19:25:30'
Q5 = q5.split(":")
hours5 = int(Q5[0])*3600
minutes5 = int(Q5[1])*60
seconds5 = int(Q5[2])

q6 = '03:10:15'
Q6 = q6.split(":")
hours6 = int(Q6[0])*3600
minutes6 = int(Q6[1])*60
seconds6 = int(Q6[2])

a7 =  hours5 + minutes5 + seconds5
a8 =  hours6 + minutes6 + seconds6 + (24*60*60) #เกินเป็นอีกวัน
a9 = a8 - a7

ho = int(a9/3600)
mi = int((a9%3600)/60)
se = int(a9%60)

print(f'ตั้งแต่ 19:25:30 - 03:10:15 จะต่างกันเป็นเวลา {ho}ชั่วโมง {mi}นาที {se}วินาที')

ตั้งแต่ 19:25:30 - 03:10:15 จะต่างกันเป็นเวลา 7ชั่วโมง 44นาที 45วินาที


### ~~HW 2 , HW 2.5~~ (ของออม)

In [4]:
import numpy as np
backgroup = 5
ก้าวไกล = backgroup * np.ones((16,13))
ก้าวไกล[1,1:12] = 99
ก้าวไกล[2,1:12] = 99
ก้าวไกล[3,10:12] = 99
ก้าวไกล[4,10:12] = 99
ก้าวไกล[5,10:12] = 99
ก้าวไกล[6,10:12] = 99
ก้าวไกล[7,9:11] = 99
ก้าวไกล[8,8:10] = 99
ก้าวไกล[9,7:9] = 99
ก้าวไกล[10,6:8] = 99
ก้าวไกล[11,5:7] = 99
ก้าวไกล[12,4:6] = 99
ก้าวไกล[13,3:5] = 99
ก้าวไกล[14,2:4] = 99
ก้าวไกล[15,1:3] = 99
ก้าวไกล[4,1:9] = 99
ก้าวไกล[5,1:9] = 99
ก้าวไกล[6,7:9] = 99
ก้าวไกล[7,6:8] = 99
ก้าวไกล[8,5:7] = 99
ก้าวไกล[9,4:6] = 99
ก้าวไกล[10,3:5] = 99
ก้าวไกล[11,2:4] = 99
ก้าวไกล[12,1:3] = 99
ก้าวไกล[13,1:2] = 99
ก้าวไกล

array([[ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 5., 99., 99., 99., 99., 99., 99., 99., 99., 99., 99., 99.,  5.],
       [ 5., 99., 99., 99., 99., 99., 99., 99., 99., 99., 99., 99.,  5.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5., 99., 99.,  5.],
       [ 5., 99., 99., 99., 99., 99., 99., 99., 99.,  5., 99., 99.,  5.],
       [ 5., 99., 99., 99., 99., 99., 99., 99., 99.,  5., 99., 99.,  5.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5., 99., 99.,  5., 99., 99.,  5.],
       [ 5.,  5.,  5.,  5.,  5.,  5., 99., 99.,  5., 99., 99.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5., 99., 99.,  5., 99., 99.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5., 99., 99.,  5., 99., 99.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5., 99., 99.,  5., 99., 99.,  5.,  5.,  5.,  5.,  5.],
       [ 5.,  5., 99., 99.,  5., 99., 99.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 5., 99., 99.,  5., 99., 99.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 5., 99.,  5., 99., 99.,  5., 

## HW 2
1. สร้าง array ที่เป็นรูป โลโกพักก้าวไกล (ของโอมมี่)

In [5]:
import numpy as np

def print_kaokai(numbg = 0):
  int_bg = int(numbg)
  num_logo = 99
  MFP_17 = int_bg*np.ones((17,17))

  #outter 7
  #ขอบบน ---
  MFP_17[0:1, 0:17] = num_logo
  MFP_17[1:2, 1:16] = num_logo

  # /
  MFP_17[1:3, 14:16] = num_logo
  MFP_17[3:5, 13:15] = num_logo
  MFP_17[5:7, 12:14] = num_logo
  MFP_17[7:9, 11:13] = num_logo
  MFP_17[9:11, 10:12] = num_logo
  MFP_17[11:13, 9:11] = num_logo
  MFP_17[13:15, 8:10] = num_logo

  # เก็บหาง
  MFP_17[14:15, 7:10] = num_logo
  MFP_17[15:17, 8:9] = num_logo


  #inner 7
  #ขอบบน ---
  MFP_17[4:5, 2:11] = num_logo
  MFP_17[5:6, 3:10] = num_logo

  # /
  MFP_17[5:7, 8:10] = num_logo
  MFP_17[7:9, 7:9] = num_logo
  MFP_17[9:11, 6:8] = num_logo

  #เก็บหาง
  MFP_17[10:11, 5:8] = num_logo
  MFP_17[11:13, 6:7] = num_logo
  print(MFP_17)

print_kaokai(5)

[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 5. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5. 99. 99.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5. 99. 99.  5.  5.]
 [ 5.  5. 99. 99. 99. 99. 99. 99. 99. 99. 99.  5.  5. 99. 99.  5.  5.]
 [ 5.  5.  5. 99. 99. 99. 99. 99. 99. 99.  5.  5. 99. 99.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5. 99. 99.  5.  5. 99. 99.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5. 99. 99.  5.  5. 99. 99.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5. 99. 99.  5.  5. 99. 99.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5. 99. 99.  5.  5. 99. 99.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5. 99. 99. 99.  5.  5. 99. 99.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5. 99.  5.  5. 99. 99.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5. 99.  5.  5. 99. 99.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5. 99. 99.  5.  5.  5.  5.  5.  5.  5.]
 [ 5. 

In [6]:
print_kaokai() #แบบไม่ใส่พื้นหลัง 2

[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 0. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 99. 99.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 99. 99.  0.  0.]
 [ 0.  0. 99. 99. 99. 99. 99. 99. 99. 99. 99.  0.  0. 99. 99.  0.  0.]
 [ 0.  0.  0. 99. 99. 99. 99. 99. 99. 99.  0.  0. 99. 99.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 99. 99.  0.  0. 99. 99.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 99. 99.  0.  0. 99. 99.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 99. 99.  0.  0. 99. 99.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 99. 99.  0.  0. 99. 99.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 99. 99. 99.  0.  0. 99. 99.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 99.  0.  0. 99. 99.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 99.  0.  0. 99. 99.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 99. 99.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 

## HW2.5
สร้าง Function เพื่อ print logo พรรคก้าวไกล โดย input พื้นหลังได้ (ของโอมมี่)

In [7]:
print_kaokai(9) #แบบใส่พื้นหลัง 2.5

[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 9. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.  9.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9. 99. 99.  9.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9. 99. 99.  9.  9.]
 [ 9.  9. 99. 99. 99. 99. 99. 99. 99. 99. 99.  9.  9. 99. 99.  9.  9.]
 [ 9.  9.  9. 99. 99. 99. 99. 99. 99. 99.  9.  9. 99. 99.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9.  9.  9. 99. 99.  9.  9. 99. 99.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9.  9. 99. 99.  9.  9. 99. 99.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9.  9. 99. 99.  9.  9. 99. 99.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9. 99. 99.  9.  9. 99. 99.  9.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9. 99. 99. 99.  9.  9. 99. 99.  9.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9. 99.  9.  9. 99. 99.  9.  9.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9. 99.  9.  9. 99. 99.  9.  9.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9.  9.  9. 99. 99.  9.  9.  9.  9.  9.  9.  9.]
 [ 9. 

## HW 3
จากdata1 อยากรู้ว่า

1. รายการที่แพงและถูกที่สุดคือรายการไหน
2. รายการขุดลอกคูคลองของ 'สำนักงานเขตคลองสาน' และ 'สำนักงานเขตคลองสามวา'
3. จากข้อ 2 เขตไหนใช้งบประมาณ เยอะกว่ากัน
4. Core Budget ไหน ("12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม','17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร','28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต') มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด

ข้อที่ 1 รายการที่แพงและถูกที่สุดคือรายการไหน

In [21]:
data1_max = data1['Approved_buget'].max()
data1_min = data1['Approved_buget'].min()
data1[(data1['Approved_buget'] == data1_max) | (data1['Approved_buget'] == data1_min)]

Budget_resource  Issue_No  Fiscal_year  Department_code  \
576     งบเพิ่มเติม         1           66         11000000   
612     งบเพิ่มเติม         1           66         50180000   
613     งบเพิ่มเติม         1           66         50180000   
631     งบเพิ่มเติม         1           66         50240000   

                 Department Core_budget_code Expenditure_category  \
576        สำนักการระบายน้ำ              NaN              งบลงทุน   
612       สำนักงานเขตธนบุรี              NaN              งบลงทุน   
613       สำนักงานเขตธนบุรี              NaN              งบลงทุน   
631  สำนักงานเขตราษฎร์บูรณะ              NaN              งบลงทุน   

                                             Item_name  Approved_buget  
576  ขุดลอกคลองพระยาสุเรนทร์ จากคลองหกวาถึงคลองบางช...        28500000  
612  ขุดลอกลำกระโดงอำนวยสุข จากคลองบางกอกใหญ่ถึงสุด...               0  
613  ขุดลอกคลองแยกวัดประดู่ จากคลองบางกอกใหญ่ถึงคลอ...               0  
631   ขุดลอกคลองต้นโศกจากคลองราษฎร์บูรณะถึงคลองแจงร้อน               0

ข้อที่ 2 รายการขุดลอกคูคลองของ 'สำนักงานเขตคลองสาน' และ 'สำนักงานเขตคลองสามวา'

In [22]:
df = pd.DataFrame(data1,columns=['Department','Item_name'])
df.set_index('Department', inplace=True)
result = df.loc[["สำนักงานเขตคลองสามวา","สำนักงานเขตคลองสาน"],['Item_name']]
result

Item_name
Department                                                             
สำนักงานเขตคลองสามวา  ขุดลอกคลองสามตะวันตก จากคลองสามวา ถึงคลองพระยา...
สำนักงานเขตคลองสามวา  ขุดลอกคลองสี่ตะวันตก จากคลองสามวา ถึงคลองพระยา...
สำนักงานเขตคลองสามวา  ขุดลอกลำรางวัดแป้นทอง จากคลองสี่ตะวันตก ถึงคลอ...
สำนักงานเขตคลองสามวา  ขุดลอกลำรางครูพัว จากคลองสองตะวันตก ถึงคลองหนึ...
สำนักงานเขตคลองสามวา     ขุดลอกลำรางตาชม จากคลองลำควายตาย ถึงคลองบางชัน
สำนักงานเขตคลองสามวา  ขุดลอกคลองเจ๊ก จากคลองหนึ่งตะวันตก ถึงสุดเขตคล...
สำนักงานเขตคลองสามวา  ขุดลอกคลองซอยเชื่อมคลองลำแบนกับคลองหนองระแหง จ...
สำนักงานเขตคลองสามวา                                   ขุดลอกลำรางตาเชย
สำนักงานเขตคลองสามวา                              ขุดลอกลำรางไทยเอราวัณ
สำนักงานเขตคลองสามวา                             ขุดลอกคลองหนึ่งตะวันตก
สำนักงานเขตคลองสามวา                               ขุดลอกคลองสองตะวันตก
สำนักงานเขตคลองสามวา                                   ขุดลอกคลองกีบหมู
สำนักงานเขตคลองสามวา                                 ขุดลอกคลองลำกะโหลก
สำนักงานเขตคลองสามวา                                 ขุดลอกคลองผักกะเฉด
สำนักงานเขตคลองสามวา                            ขุดลอกคลองบึงทรายกองดิน
สำนักงานเขตคลองสามวา                                  ขุดลอกลำรางซาฟารี
สำนักงานเขตคลองสามวา                                ขุดลอกลำรางตาจันทร์
สำนักงานเขตคลองสาน                                   ขุดลอกคูน้ำสารภี 1
สำนักงานเขตคลองสาน                              ขุดลอกคลองวัดทองเพลง\n 
สำนักงานเขตคลองสาน    ขุดลอกลำกระโดงชุมชนสองร้อยห้อง\nจากบริเวณบ้านเ...
สำนักงานเขตคลองสาน    ขุดลอกคลองวัดทองธรรมชาติและคลองแยกคลองวัดทองธร...
สำนักงานเขตคลองสาน                                     ขุดลอกคลองโรงปลา
สำนักงานเขตคลองสาน                           ขุดลอกลำกระโดงซอยอิสรภาพ 3
สำนักงานเขตคลองสาน         ขุดลอกคลองหลังวัดพิชัยญาติและคลองวัดน้อยเก่า
สำนักงานเขตคลองสาน                                  ขุดลอกคลองพระยาเกษม
สำนักงานเขตคลองสาน                      ขุดลอกคลองข้างโรงเรียนปทุมวิทยา
สำนักงานเขตคลองสาน    ขุดลอกคลองวัดน้อยใหม่จากแยกบ้านแขกถึงคลองสมเด็...
สำนักงานเขตคลองสาน    ขุดลอกคลองโรงหนัง จากคลองบางไส้ไก่ถึงแม่น้ำเจ้...
สำนักงานเขตคลองสาน    ขุดลอกคลองข้างโรงน้ำแข็ง จากสุดระยะคลองถึงแม่น...
สำนักงานเขตคลองสาน    ขุดลอกคลองข้างวัดอนงค์ จากคลองหลัง\nวัดพิชัยญา...

ข้อที่ 3 จากข้อ 2 เขตไหนใช้งบประมาณ เยอะกว่ากัน

In [23]:
df3 = pd.DataFrame(data1)
result3 = df3.groupby('Department')['Approved_buget'].aggregate(['min','max'])
result3[0:3][1:3]

min      max
Department                           
สำนักงานเขตคลองสาน     80000  2218000
สำนักงานเขตคลองสามวา  452300  9832000

ข้อที่ 4 Core Budget ไหน ("12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม','17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร','28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต') มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด

In [24]:
Core_data1 = data1.dropna()
CoreBudget_data1 = Core_data1[Core_data1['Core_budget_code'] != '-']
CoreBudget_data1_12 =CoreBudget_data1[CoreBudget_data1['Core_budget_code'] == '12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม']
CoreBudget_data1_28 =CoreBudget_data1[CoreBudget_data1['Core_budget_code'] == '28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต']
CoreBudget_data1_17 =CoreBudget_data1[CoreBudget_data1['Core_budget_code'] == '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร']
CoreBudget = []

x=set(CoreBudget_data1['Core_budget_code'])
for n in x:
  CoreBudget.append(n)
CoreBudget_data1_12_MEAN =CoreBudget_data1_12['Approved_buget'].mean()
CoreBudget_data1_17_MEAN =CoreBudget_data1_17['Approved_buget'].mean()
CoreBudget_data1_28_MEAN =CoreBudget_data1_28['Approved_buget'].mean()

if (CoreBudget_data1_12_MEAN > CoreBudget_data1_17_MEAN ) & (CoreBudget_data1_12_MEAN > CoreBudget_data1_28_MEAN ):
  print(f'รายการนี้ {CoreBudget[2]} มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด {CoreBudget_data1_12_MEAN}')
elif (CoreBudget_data1_17_MEAN > CoreBudget_data1_12_MEAN ) & (CoreBudget_data1_17_MEAN > CoreBudget_data1_28_MEAN ):
  print(f'รายการนี้ {CoreBudget[0]} มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด {CoreBudget_data1_17_MEAN}')
elif (CoreBudget_data1_28_MEAN > CoreBudget_data1_12_MEAN ) & (CoreBudget_data1_28_MEAN > CoreBudget_data1_17_MEAN ):
  print(f'รายการนี้ {CoreBudget[1]} มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด {CoreBudget_data1_28_MEAN}')

รายการนี้ 12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด 1837500.0


## HW 4
จากตาราง sep_oct_df

1. งบประมาณประจำหรืองบประมาณลงทุน สูงกว่ากัน
2. งบรวม เดือน oct หรืแ sep อันไหนมากกว่ากัน
3. แก้ค่า missing พร้อมทั้งให้เหตุผล
4. เดือนไหนเบิกจ่ายมากกว่ากัน (การใช้จ่าย (PO+เบิกจ่าย))


## Quiz 1

## Quiz 2

กำหนด list เป็นประโยคคำว่า "Department of Statistics, Faculty of Science, Khon Kaen University, Thailand"

1. ตัดมาเฉพาะคำว่า Faculty of Science
2. ตัดแบบเว้นทีละ 3 ตัวอักษร
3. ตัดคำว่า Khon Kaen University ออกมาแล้วเขียนกลับหลัง

In [27]:
list_t = ["Department of Statistics, Faculty of Science, Khon Kaen University, Thailand"]
qtext = "Department of Statistics, Faculty of Science, Khon Kaen University, Thailand"
list_t2 = list("Department of Statistics, Faculty of Science, Khon Kaen University, Thailand")
list_t2

['D',
 'e',
 'p',
 'a',
 'r',
 't',
 'm',
 'e',
 'n',
 't',
 ' ',
 'o',
 'f',
 ' ',
 'S',
 't',
 'a',
 't',
 'i',
 's',
 't',
 'i',
 'c',
 's',
 ',',
 ' ',
 'F',
 'a',
 'c',
 'u',
 'l',
 't',
 'y',
 ' ',
 'o',
 'f',
 ' ',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e',
 ',',
 ' ',
 'K',
 'h',
 'o',
 'n',
 ' ',
 'K',
 'a',
 'e',
 'n',
 ' ',
 'U',
 'n',
 'i',
 'v',
 'e',
 'r',
 's',
 'i',
 't',
 'y',
 ',',
 ' ',
 'T',
 'h',
 'a',
 'i',
 'l',
 'a',
 'n',
 'd']

In [29]:
qlist = qtext.split(', ')
qlist
list_t
type(list_t)
type(qtext)
type(list_t2)

list

In [31]:
list_q2 = qtext.split(', ')
list_q2

['Department of Statistics',
 'Faculty of Science',
 'Khon Kaen University',
 'Thailand']

ข้อที่ 1 ตัดมาเฉพาะคำว่า Faculty of Science

In [33]:
list_q2[0]

'Department of Statistics'

ข้อที่ 2 ตัดแบบเว้นทีละ 3 ตัวอักษร

In [34]:
list_ch2 = list_t[::3]
list_ch2

['Department of Statistics, Faculty of Science, Khon Kaen University, Thailand']

ข้อที่ 3 ตัดคำว่า Khon Kaen University ออกมาแล้วเขียนกลับหลัง

In [35]:
list_q2[2]
list_ch3 = list_q2[2][::-1]
list_ch3

'ytisrevinU neaK nohK'

## Quiz3
อยากได้รายการที่ได้รับอนุมัติงบมากกว่า 1 ล้านบาท แต่ไม่เกิน 2 ล้านบาท

In [14]:

import pandas as pd #ฟังก์ชันเฉพาะต้องรันก่อน

In [8]:
from google.colab import drive
drive.mount('/content/drive')  # mount =  เชื่อมไดร์ฟ

Mounted at /content/drive


In [15]:
data0 = pd.read_csv('/content/drive/MyDrive/DataViz23Data/BKK.csv')

In [16]:
data1 = pd.read_csv('/content/drive/MyDrive/DataViz23Data/BKK.csv')
data1.head()

Budget_resource  Issue_No  Fiscal_year  Department_code        Department  \
0       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
1       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
2       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
3       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
4       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   

                                    Core_budget_code Expenditure_category  \
0  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
1  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
2  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
3  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
4  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   

                                           Item_name  Approved_buget  
0        ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ         1193000  
1  ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...         1100000  
2          ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข         3075000  
3  ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...         6240000  
4  ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...         2685000

In [20]:
data1[(data1['Approved_buget']>1000000) & (data1['Approved_buget'] <= 2000000)] #Answer

Budget_resource  Issue_No  Fiscal_year  Department_code  \
0         งบประจำปี         0           62         11000000   
1         งบประจำปี         0           62         11000000   
5         งบประจำปี         0           62         11000000   
22        งบประจำปี         0           63         11000000   
25        งบประจำปี         0           63         11000000   
..              ...       ...          ...              ...   
660     งบเพิ่มเติม         1           66         50350000   
662     งบเพิ่มเติม         1           66         50350000   
665     งบเพิ่มเติม         1           66         50350000   
666     งบเพิ่มเติม         1           66         50360000   
670     งบเพิ่มเติม         1           66         50360000   

             Department                                   Core_budget_code  \
0      สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
1      สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
5      สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
22     สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
25     สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
..                  ...                                                ...   
660  สำนักงานเขตบางพลัด                                                NaN   
662  สำนักงานเขตบางพลัด                                                NaN   
665  สำนักงานเขตบางพลัด                                                NaN   
666   สำนักงานเขตจอมทอง                                                NaN   
670   สำนักงานเขตจอมทอง                                                NaN   

    Expenditure_category                                          Item_name  \
0                งบลงทุน        ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ   
1                งบลงทุน  ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...   
5                งบลงทุน  ขุดลอกคลองราษฎร์สามัคคีจากคลองทวีวัฒนาถึงคลองม...   
22               งบลงทุน      ขุดลอกคลองนางหงษ์จากคลองแสนแสบถึงถนนบรรทัดทอง   
25               งบลงทุน  ขุดลอกคลองราษฎร์บูรณะจากแม่น้ำเจ้าพระยาถึงสวนธ...   
..                   ...                                                ...   
660              งบลงทุน                                 ขุดลอกคลองสะพานยาว   
662              งบลงทุน         ขุดลอกคลองบางรักและคูน้ำซอยจรัญสนิทวงศ์ 89   
665              งบลงทุน                           ขุดลอกคลองวัดน้อยนางหงษ์   
666              งบลงทุน  ขุดลอกคลองลัดบางสะแก (1),(2) จากคลองบางค้อและค...   
670              งบลงทุน  ขุดลอกลำกระโดงสาธารณประโยชน์แยกคลองต้นไทร (3),...   

     Approved_buget  
0           1193000  
1           1100000  
5           1207000  
22          1508000  
25          1975000  
..              ...  
660         1756000  
662         1859000  
665         1187000  
666         1581000  
670         1388000  

[132 rows x 9 columns]